spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/site_db
    username: root
    password: 3216
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
params:
  productsPerPage: 8